version: '3'

networks:
  production-network:

services:

  zookeeper:
    image: "confluentinc/cp-zookeeper:5.2.1"
    volumes:
      - zookeeper-volume:/var/lib/zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_SYNC_LIMIT: 2
    networks:
      - production-network

  kafka:
    image: "confluentinc/cp-kafka:5.2.1"
    volumes:
      - kafka-volume:/var/lib/kafka
    ports:
      - 9092:9092
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    networks:
      - production-network

  postgres:
    image: 'postgres:9.6-alpine'
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
      POSTGRES_DB: keycloak
      POSTGRES_HOST: postgres
    networks:
      - production-network

  postgres_proposta:
    image: 'postgres:9.6-alpine'
    volumes:
      - aplicacao-volume:/var/lib/postgresql/data
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: propostas
      POSTGRES_PASSWORD: password
      POSTGRES_DB: propostas
      POSTGRES_HOST: postgres
    networks:
      - production-network

  postgres_transacao:
    image: 'postgres:9.6-alpine'
    volumes:
      - transacao-volume:/var/lib/postgresql/data
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: transacao
      POSTGRES_PASSWORD: password
      POSTGRES_DB: transacao
      POSTGRES_HOST: postgres
    networks:
      - production-network

  keycloak:
    image: jboss/keycloak:11.0.0
    volumes:
      - keycloak-volume:/var/lib/keycloak
    ports:
      - 18443:8443
      - 18080:8080
      - 19990:9990
    depends_on:
      # Just a delay to wait for postgres! This is not recommended!
      - jaeger
      - kafka
      - zookeeper
      - contas
      - analise
      - transacoes
      - postgres
    environment:
      DB_VENDOR: postgres
      DB_ADDR: postgres
      DB_PORT: 5432
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: Pa55w0rd
      POSTGRES_PORT_5432_TCP_ADDR: 127.0.0.1
    restart: on-failure
    networks:
      - production-network

  analise:
    image: 'zupacademy/analise-financeira'
    volumes:
      - analise-volume:/var/lib/analise
    ports:
      - 9999:9999
    environment:
      SERVER_PORT: 9999
      LOG_LEVEL: INFO
      URL_SISTEMA_CARTAO: http://contas:8888/api/cartoes
      JAEGER_ENDPOINT: http://jaeger:14268/api/traces
    networks:
      - production-network

  contas:
    image: 'zupacademy/contas'
    volumes:
      - contas-volume:/var/lib/
    ports:
      - 8888:8888
    environment:
      SERVER_PORT: 8888
      LOG_LEVEL: INFO
      JAEGER_ENDPOINT: http://jaeger:14268/api/traces
    networks:
      - production-network

  transacoes:
    image: 'zupacademy/transacoes'
    volumes:
      - transacoes-volume:/var/lib/jaeger
    ports:
      - 7777:7777
    depends_on:
      - kafka
    environment:
      SERVER_PORT: 7777
      LOG_LEVEL: INFO
      KAFKA_HOST: "kafka:29092"
      JAEGER_ENDPOINT: http://jaeger:14268/api/traces
    networks:
      - production-network

  jaeger:
    image: jaegertracing/all-in-one:1.21.0
    volumes:
      - jaeger-volume:/var/lib/jaeger
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 14250:14250
      - 9411:9411
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: 9411
    networks:
      - production-network

  vault:
    image: vault:1.5.3
    volumes:
      - valt-volume:/var/lib/valt
    ports:
      - 8200:8200
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: ee413645-dbe8-4848-afc6-6bb2768ada75
      VAULT_TOKEN: ee413645-dbe8-4848-afc6-6bb2768ada75
      VAULT_ADDR: http://127.0.0.1:8200
    networks:
      - production-network

volumes:
  postgres-volume:
  aplicacao-volume:
  transacao-volume:
  contas-volume:
  valt-volume:
  jaeger-volume:
  transacoes-volume:
  analise-volume:
  keycloak-volume:
  kafka-volume:
  zookeeper-volume: